name: Crowdin Action

# 参考 https://github.com/LibChecker/LibChecker/blob/master/.github/workflows/translation.yml

on:
  push:
    branches: [ "main" ]
    paths:
      - app/src/main/res/values/strings.xml
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest
    if: github.repository == 'Super12138/VerveDo'

    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1
        with:
          fetch-depth: 0

      - name: Crowdin Action
        uses: crowdin/github-action@v3.1.0
        with:
          upload_sources: true
          upload_translations: true
          download_translations: true
          create_pull_request: true
          pull_request_base_branch_name: main
          localization_branch_name: crowdin-translations
          config: crowdin.yml
          crowdin_branch_name: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
